<?php $imageURI = get_template_directory_uri() . '/public/images/mails/'; ?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
</head>
<body style="margin:0;font-family:'Lato',sans-serif;color:#fff;font-style:normal;line-height:normal;">
<table style="width:100%;max-width:768px;margin:0 auto;background-color:#3023AE;background:linear-gradient(165.02deg, #3023AE, #C86DD7);border-spacing:0;border-collapse:collapse;">
    <tbody>
    <tr>
        <td></td>
        <td style="max-width:580px;margin:0 auto;padding:0;display:block;clear:both;">
            <div>
                <table style="width:100%;border-spacing:0;border-collapse:collapse;">
                    <tbody>
                    <tr style="text-align:center;">
                        <td colspan="3">
                            <img src="<?= $imageURI; ?>Logo.png" alt="Logo"
                                 style="height:auto;width:184px;padding:20px 0;">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="padding:0;margin:0;">
                            <img src="<?= $imageURI; ?>image-2-1.jpg" alt="image-2-1"
                                 style="height:auto;width:100%;display:block;">
                        </td>
                    </tr>
                    <tr style="background: #fff">
                        <td colspan="3">
                            <table style="max-width:490px;margin:0 auto;border-spacing:0;border-collapse:collapse;">
                                <tbody>
                                <tr style="text-align:center;max-width:490px">
                                    <td style="font-family:'Lato',sans-serif;">
                                        <span style="font-weight:900;line-height:24px;font-size:1.25em;text-transform:uppercase;color:#FF8200;display:block;padding-top:20px">
                                            Уважаемые клиенты компании</span>
                                        <span style="font-weight:900;line-height:24px;font-size:1.25em;text-transform:uppercase;color:#FF8200;display:block;">
                                            GIC Canada Global immigration corp</span>
                                        <span style="font-weight:bold;line-height:20px;font-size:1.25em;color:#00003A;display:block;padding-top:10px;padding-bottom:20px">
                                            Поздравляем вас с открытием дела!</span>
                                        <span style="line-height:20px;font-size:.875em;color:#00003A;display:block;padding-bottom:40px;">
                                            В течении 7 рабочих дней, ваше дело будет рассматриваться нашими специалистами,
                                            с целью найти для вас самый подходящий вариант из всех существующих программ, исходя из вашей первоначальной цели.</span>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="padding:0; margin:0;">
                            <img src="<?= $imageURI; ?>image-2-2_3.jpg" alt="image-2-2_3"
                                 style="height:auto;width:100%;display:block;">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3"
                            style="background-color:#852EF6;background:linear-gradient(53.56deg, #852EF6, #00FFD4)">
                            <table style="border-spacing:0;border-collapse:collapse;max-width:580px;margin:0 auto;">
                                <tbody>
                                <tr style="text-align:left;">
                                    <td style="color:#fff;font-family:'Lato',sans-serif;max-width:490px;margin:0 auto;">
                                        <div style="padding-top:20px;padding-bottom:40px">
                                            <p style="line-height:20px;font-size:1em;margin-top:0">
                                                В Канаде существует более чем 60 возможных программ с помощью которых у
                                                вас есть возможность иммигрировать.
                                                После изучения вашего дела, мы предложим вам наиболие реальные варианты
                                                выезда.
                                            </p>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="padding:0;margin:0;">
                            <img src="<?= $imageURI; ?>image-2-3.jpg" alt="image-2-3"
                                 style="height:auto;width:100%;display:block;">
                        </td>
                    </tr>
                    <tr style="background: #fff">
                        <td colspan="3">
                            <table style="max-width:490px;margin:0 auto;border-spacing:0;border-collapse:collapse;">
                                <tbody>
                                <tr style="text-align:left;max-width:490px">
                                    <td style="font-family:'Lato',sans-serif;">
                                        <div style="padding-top:20px;padding-bottom:40px">
                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block">
                                                После, вам на почту придёт договор и документальное, развернутое
                                                объяснение с анализом ваших возможностей и вариантов по программам.
                                                Далее наш менеджер свяжется с вами и детально объяснит специфику вашей
                                                программы, даст ответ при наличии у вас дополнительных вопросов. </p>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="padding:0;margin:0;">
                            <img src="<?= $imageURI; ?>image-2-4.jpg" alt="image-2-4"
                                 style="height:auto;width:100%;display:block;">
                        </td>
                    </tr>
                    <tr style="background: #fff">
                        <td colspan="3"
                            style="background-color:#852EF6;background:linear-gradient(53.56deg, #852EF6, #00FFD4)">
                            <table style="border-spacing:0;border-collapse:collapse;max-width:580px;margin:0 auto;">
                                <tbody>
                                <tr style="text-align:left;">
                                    <td style="color:#fff;font-family:'Lato',sans-serif;max-width:490px;margin:0 auto;display:block">
                                        <div style="padding-bottom:40px;padding-top:20px">
                                            <p style="line-height:20px;font-size:1em;margin-top:0">
                                                Вы подписываете договор на одобренную программу, и мы начинаем работать.
                                                В течении нескольких дней с вами связывается менеджер и координированно
                                                заниматься сбором документов вместе с вами. В зависимости от программы,
                                                вам дается развернутое объяснение о том, как записываются на экзамены
                                                английского языка, как готовить документы к подаче в Министерство
                                                образования Канады для их подтверждения, как заниматься поиском
                                                работодателя, также помогает разместить резюме в Job Bank Сanada, дает
                                                первичное объяснение и консультирует.
                                            </p>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="padding:0;margin:0;">
                            <img src="<?= $imageURI; ?>image-2-5.jpg" alt="image-2-5"
                                 style="height:auto;width:100%;display:block;">
                        </td>
                    </tr>
                    <tr style="background: #fff">
                        <td colspan="3">
                            <table style="max-width:490px;margin:0 auto;border-spacing:0;border-collapse:collapse;">
                                <tbody>
                                <tr style="text-align:left;max-width:490px">
                                    <td style="font-family:'Lato',sans-serif;">
                                        <div style="padding-top:20px;padding-bottom:40px">
                                          <span style="font-weight:900;line-height:24px;font-size:1.25em;text-transform:uppercase;
                                            color:#0076FF;display:block;border-bottom: 1px solid #0076FF;padding-bottom:15px">Вы также:</span>

                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block;border-bottom: 1px solid #CFCFCF;padding-bottom:15px">
                                                Получаете свой личный иммиграционный файл в компании и доступ к нему на
                                                нашем сайте</p>

                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block;border-bottom: 1px solid #CFCFCF;padding-bottom:15px">
                                                Всегда сможете зайти в личный файл и проверить статус вашего дела</p>

                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block;border-bottom: 1px solid #CFCFCF;padding-bottom:15px">
                                                Наша система будет оповещать вас о каждом изменении или обновлении в
                                                вашем деле с помощью СМС на ваш мобильный телефон</p>

                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block;border-bottom: 1px solid #CFCFCF;padding-bottom:15px">
                                                Будете знать в онлайн режиме что происходит с вашими документами и на
                                                какой стадии подачи они находиться,
                                                таким образом это значительно сократит сроки ожидания и оптимизирует
                                                весь процесс</p>

                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block;">
                                                Сможете контролировать каждый этап работы, поэтому вы всегда держите
                                                руку на пульсе вашего дела</p>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="padding:0;margin:0;">
                            <img src="<?= $imageURI; ?>image-2-6.jpg" alt="image-2-6"
                                 style="height:auto;width:100%;display:block;">
                        </td>
                    </tr>
                    <tr style="background: #fff">
                        <td colspan="3">
                            <table style="max-width:490px;margin:0 auto;border-spacing:0;border-collapse:collapse;">
                                <tbody>
                                <tr style="text-align:left;max-width:490px">
                                    <td style="font-family:'Lato',sans-serif;">
                                        <div style="padding-bottom:40px;padding-top:20px">
                                            <span style="font-weight:900;line-height:24px;font-size:1.25em;text-transform:uppercase;color:#0076FF;display:block;">
                                            Персональный менеджер на весь период процесса</span>

                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block;">
                                                К вашему делу прикрепляться специалист, который будет вести ваше дело на
                                                протяжении всего процесса оформления. Он станет вашим помощником,
                                                будет с вами на связи и с радостью решит любой вопрос или даст
                                                необходимую рекомендацию, зная всю специфику вашего дела от начала и до
                                                завершения всего процесса.</p>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="padding:0;margin:0;">
                            <img src="<?= $imageURI; ?>image-2-7.jpg" alt="image-2-7"
                                 style="height:auto;width:100%;display:block;">
                        </td>
                    </tr>
                    <tr style="background: #fff">
                        <td colspan="3">
                            <table style="max-width:490px;margin:0 auto;border-spacing:0;border-collapse:collapse;">
                                <tbody>
                                <tr style="text-align:left;max-width:490px">
                                    <td style="font-family:'Lato',sans-serif;">
                                        <div style="padding-bottom:40px;padding-top:20px">
                                            <span style="font-weight:900;line-height:24px;font-size:1.25em;text-transform:uppercase;color:#0076FF;display:block;">
                                            Юридическая поддержка</span>

                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block;">
                                                Если по специфике вашего дела необходимо будет участие канадского
                                                адвоката,
                                                мы предоставим вам надежного адвоката, который окажет вам всю
                                                необходимую юридическую
                                                поддержку и приготовит необходимые заверения документов.</p>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="padding:0;margin:0;">
                            <img src="<?= $imageURI; ?>image-2-8_2.jpg" alt="image-2-8_2"
                                 style="height:auto;width:100%;display:block;">
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </td>
        <td></td>
    </tr>
    </tbody>
</table>
<table style="width:100%;max-width:768px;margin:0 auto;border-spacing:0;border-collapse:collapse;background:#001733;">
        <tbody>
        <tr>
            <td></td>
            <td style="max-width:580px;margin:0 auto;padding:0;display:block;clear:both;">
                <div>
                    <table style="width:100%;border-spacing:0;border-collapse:collapse;">
                        <tbody>
                        <tr>
                            <td colspan="3"
                                style="background-color:#852EF6;background:linear-gradient(53.56deg, #852EF6, #00FFD4)">
                                <table style="border-spacing:0;border-collapse:collapse;max-width:580px;margin:0 auto;">
                                    <tbody>
                                    <tr style="text-align:left;">
                                        <td style="color:#fff;font-family:'Lato',sans-serif;max-width:490px;margin:0 auto;">
                                            <div style="padding-bottom:40px;padding-top:20px;">
                                            <span style="font-weight:900;line-height:24px;font-size:1.25em;text-transform:uppercase;
                                            display:block;padding-bottom:15px;border-bottom:1px solid #fff;">Этапы работы</span>

                                                <p style="line-height:20px;font-size:1em;margin-top:0;padding-bottom:15px;padding-top:15px;border-bottom:1px solid #fff;">
                                                    1) Регистрируем ваше дело в Министерстве Иммиграции, и вы получаете
                                                    сой личный файл
                                                </p>
                                                <p style="line-height:20px;font-size:1em;padding-bottom:15px;border-bottom:1px solid #fff">
                                                    2) Подаем ваши документы в Министерство Образования для
                                                    подтверждения всех ваших дипломов и выписок с оценками
                                                </p>
                                                <p style="line-height:20px;font-size:1em;margin-bottom:0;padding-bottom:15px;border-bottom:1px solid #fff">
                                                    3) Регистрируем вас в Job Bank Сanada и размещаем ваше резюме для
                                                    поиска работодателя, что даст вам дополнительные баллы
                                                </p>

                                                <p style="line-height:20px;font-size:1em;margin-top:0;padding-bottom:15px;border-bottom:1px solid #fff">
                                                    4) Подаем вас дополнительно с вашего согласия на провинциальную
                                                    иммиграционную программу Nominee Program что добавит вам
                                                    дополнительно баллы.
                                                </p>
                                                <p style="line-height:20px;font-size:1em;padding-bottom:15px;border-bottom:1px solid #fff">
                                                    5) Подаем ваше дело в посольство в стране вашего проживания, вы
                                                    подписываете декларации и получаете формы на прохождение медицинской
                                                    комиссии
                                                    (только для проверки, заболеваний, которые могут навредить обществу
                                                    в Канаде: туберкулез, ВИЧ и т.п.)
                                                </p>
                                                <p style="line-height:20px;font-size:1em;margin-bottom:0;">
                                                    6) Вы получаете иммиграционные визы в зависимости от программы, в
                                                    Канаде вас встречают наши представители, помогают с размещением,
                                                    адаптацией, открытием счетов в банках, получением Permanent Resident
                                                    Card, оформлением социального номера и медицинского страхования,
                                                    помогут записать ваших детей в садики и школы, и начать новую жизнь
                                                    в одной из самых развитых стран мира.
                                                </p>
                                            </div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        </tbody>
                    </table>
	                <?php get_template_part('template-parts/emails/mail', 'footer');?>
                </div>
            </td>
            <td></td>
        </tr>
        </tbody>
    </table>
</body>
</html>