<?php $imageURI = get_template_directory_uri() . '/public/images/mails/'; ?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
</head>
<body style="margin:0;font-family:'Lato',sans-serif;color:#fff;font-style:normal;line-height:normal;">
<table style="width:100%;max-width:768px;margin:0 auto;background-color:#3023AE;background:linear-gradient(165.02deg, #3023AE, #C86DD7);border-spacing:0;border-collapse:collapse;">
    <tbody>
    <tr>
        <td></td>
        <td style="max-width:580px;margin:0 auto;padding:0;display:block;clear:both;">
            <div>
                <table style="width:100%;border-spacing:0;border-collapse:collapse;">
                    <tbody>
                    <tr style="text-align:center;">
                        <td colspan="3">
                            <img src="<?= $imageURI; ?>Logo.png" alt="Logo"
                                 style="height:auto;width:184px;padding:20px 0;">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="padding:0;margin:0;">
                            <img src="<?= $imageURI; ?>image-3-1_2.jpg" alt="image-3-1_2"
                                 style="height:auto;width:100%;display:block;">
                        </td>
                    </tr>
                    <tr style="background: #fff">
                        <td colspan="3">
                            <table style="max-width:490px;margin:0 auto;border-spacing:0;border-collapse:collapse;">
                                <tbody>
                                <tr style="text-align: center;max-width:490px">
                                    <td style="font-family:'Lato',sans-serif;">
                                        <div style="padding-top:20px;padding-bottom:40px;">
                                           <span style="font-weight:900;line-height:24px;font-size:1.25em;text-transform:uppercase;color:#FF8200;display:block;padding-bottom:15px;">
                                            Мы рады начать работать над вашим делом, чтобы получить желательный результат</span>

                                            <span style="line-height:20px;font-size:.875em;color:#00003A;display:block;">
                                            Команда GIC Canada Global immigration corp качественно и быстро, проведет весь процесс и поможет вам иммигрировать,
                                                получить работу либо уехать на учебу по выбранной программе.</span>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="padding:0; margin:0;">
                            <img src="<?= $imageURI; ?>image-3-2.jpg" alt="image-3-2"
                                 style="height:auto;width:100%;display:block;">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3"
                            style="background-color:#852EF6;background:linear-gradient(53.56deg, #852EF6, #00FFD4)">
                            <table style="border-spacing:0;border-collapse:collapse;max-width:580px;margin:0 auto;">
                                <tbody>
                                <tr style="text-align:left;">
                                    <td style="color:#fff;font-family:'Lato',sans-serif;max-width:490px;margin:0 auto;">
                                        <div style="padding-bottom:40px;padding-top:20px;">
                                            <span style="font-weight:900;line-height:24px;font-size:1.25em;text-transform:uppercase;
                                            display:block;padding-bottom:15px;border-bottom:1px solid #fff;">Система продуктивного сотрудничества</span>

                                            <p style="line-height:20px;font-size:1em;margin-top:0;padding-bottom:15px;padding-top:15px;border-bottom:1px solid #fff">
                                                После подписания договора в течении 3 рабочих дней с вами связывается наш кейс менеджер, который после знакомства с вами объясняет все детали первых этапов вашего дела, и вы начинаете заниматься первичными сверками и сбором документов.
                                            </p>
                                            <p style="line-height:20px;font-size:1em;padding-bottom:15px;border-bottom:1px solid #fff">
                                                Вы получаете все необходимые назначения по изучению языков и сдачи экзаменов в зависимости от выбранной программы.
                                            </p>
                                            <p style="line-height:20px;font-size:1em;margin-bottom:0;">
                                                Вас инструктируют по правильному заполнению форм и сбору документов.
                                            </p>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="padding:0;margin:0;">
                            <img src="<?= $imageURI; ?>image-3-3.jpg" alt="image-3-3"
                                 style="height:auto;width:100%;display:block;">
                        </td>
                    </tr>
                    <tr style="background: #fff">
                        <td colspan="3">
                            <table style="max-width:490px;margin:0 auto;border-spacing:0;border-collapse:collapse;">
                                <tbody>
                                <tr style="text-align:left;max-width:490px">
                                    <td style="font-family:'Lato',sans-serif;">
                                        <div style="padding-top:20px;padding-bottom:40px">
                                          <span style="font-weight:900;line-height:24px;font-size:1.25em;text-transform:uppercase;
                                            color:#0076FF;display:block;border-bottom: 1px solid #0076FF;padding-bottom:15px">Кооперация с нами</span>

                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block;border-bottom: 1px solid #CFCFCF;padding-bottom:15px">
                                                Мы регистрируем ваш файл в Министерстве иммиграции Канады и Express Entry, с вами связывается кейс менеджер и вы вместе заполняете формы на подачу, затем формы проверяются и утверждаются начальником отдела и при необходимости проверяются так же Канадским адвокатом.</p>

                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block;border-bottom: 1px solid #CFCFCF;padding-bottom:15px">
                                                Подаем ваше дело на утверждение в Министерство образования Канады WES, с вами связывается ваш менеджер и помогает правильно собрать и подготовить документы, сделать необходимые переводы и заверения на английский язык, так же правильно их приготовить к отправке в Канаду.</p>

                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block;border-bottom: 1px solid #CFCFCF;padding-bottom:15px">
                                                Регистрируем ваше дело в Министерстве труда, с вами созывается менеджер и мы составляем для вас профессиональное резюме.</p>

                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block;border-bottom: 1px solid #CFCFCF;padding-bottom:15px">
                                                Готовим ваше дело к открытию файла в Министерстве иммиграции в Канаду, группируем весь пакет документов, заполняем вместе с вами все формы и проводим их сверки, ваше дело проверяется начальником отдела и Канадскими адвокатами, затем утверждается, и подается.</p>

                                            <p style="line-height:20px;font-size:1em;color:#00003A;display:block;">
                                                Далее ваше дело подается в посольство в стране проживания, оно будет подано и выслано либо заказной почтой, либо системой онлайн в Канадское посольство в стране вашего проживания для окончательного утверждения и получения иммиграционных виз.</p>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="padding:0;margin:0;">
                            <img src="<?= $imageURI; ?>image-3-4.jpg" alt="image-3-4"
                                 style="height:auto;width:100%;display:block;">
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </td>
        <td></td>
    </tr>
    </tbody>
</table>
<table style="width:100%;max-width:768px;margin:0 auto;border-spacing:0;border-collapse:collapse;background:#001733;">
    <tbody>
    <tr>
        <td></td>
        <td style="max-width:580px;margin:0 auto;padding:0;display:block;clear:both;">
            <div>
                <table style="width:100%;border-spacing:0;border-collapse:collapse;">
                    <tbody>
                    <tr>
                        <td colspan="3"
                            style="background-color:#852EF6;background:linear-gradient(53.56deg, #852EF6, #00FFD4)">
                            <table style="border-spacing:0;border-collapse:collapse;max-width:580px;margin:0 auto;">
                                <tbody>
                                <tr style="text-align:left;">
                                    <td style="color:#fff;font-family:'Lato',sans-serif;max-width:490px;margin:0 auto;">
                                        <div style="padding-bottom:40px;padding-top:20px;">
                                            <span style="font-weight:900;line-height:24px;font-size:1.25em;text-transform:uppercase;
                                            display:block;padding-bottom:15px;">GIC Canada Global immigration corp</span>

                                            <p style="line-height:20px;font-size:1em;margin-top:0;padding-bottom:15px;padding-top:15px">
                                                Международная Иммиграционная Корпорация
                                            </p>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>
				<?php get_template_part('template-parts/emails/mail', 'footer');?>
            </div>
        </td>
        <td></td>
    </tr>
    </tbody>
</table>
</body>
</html>