<?php

function getCities() {
	return array(
		'ON' => [
			'Barrie',
			'Belleville',
			'Brampton',
			'Brant',
			'Brantford',
			'Brockville',
			'Burlington',
			'Cambridge',
			'Clarence-Rockland',
			'Cornwall',
			'Dryden',
			'Elliot Lake',
			'Greater Sudbury',
			'Guelph',
			'Haldimand County',
			'Hamilton',
			'Kawartha Lakes',
			'Kenora',
			'Kingston',
			'Kitchener',
			'London',
			'Markham',
			'Mississauga',
			'Niagara Falls',
			'Norfolk County',
			'North Bay',
			'Orillia',
			'Oshawa',
			'Ottawa',
			'Owen Sound',
			'Pembroke',
			'Peterborough',
			'Pickering',
			'Port Colborne',
			'Prince Edward County',
			'Quinte West',
			'Sarnia',
			'Sault Ste. Marie',
			'St. Catharines',
			'St. Thomas',
			'Stratford',
			'Temiskaming Shores',
			'Thorold',
			'Thunder Bay',
			'Timmins',
			'Toronto',
			'Vaughan',
			'Waterloo',
			'Welland',
			'Windsor',
			'Woodstock'
		],
		'QC' => [
			'Acton Vale',
			'Alma',
			'Amos',
			'Amqui',
			'Asbestos',
			'Baie-Comeau',
			'Baie-D\'Urfé',
			'Baie-Saint-Paul',
			'Barkmere',
			'Beaconsfield',
			'Beauceville',
			'Beauharnois',
			'Beaupré',
			'Bedford',
			'Belleterre',
			'Beloeil',
			'Berthierville',
			'Blainville',
			'Bois-des-Filion',
			'Boisbriand',
			'Bonaventure',
			'Boucherville',
			'Brome Lake',
			'Bromont',
			'Brossard',
			'Brownsburg-Chatham',
			'Bécancour',
			'Candiac',
			'Cap-Chat',
			'Cap-Santé',
			'Carignan',
			'Carleton-sur-Mer',
			'Causapscal',
			'Chambly',
			'Chandler',
			'Chapais',
			'Charlemagne',
			'Chibougamau',
			'Château-Richer',
			'Châteauguay',
			'Clermont',
			'Coaticook',
			'Contrecoeur',
			'Cookshire-Eaton',
			'Coteau-du-Lac',
			'Cowansville',
			'Côte Saint-Luc',
			'Danville',
			'Daveluyville',
			'Delson',
			'Desbiens',
			'Deux-Montagnes',
			'Disraeli',
			'Dolbeau-Mistassini',
			'Dollard-des-Ormeaux',
			'Donnacona',
			'Dorval',
			'Drummondville',
			'Dunham',
			'Duparquet',
			'Dégelis',
			'East Angus',
			'Estérel',
			'Farnham',
			'Fermont',
			'Forestville',
			'Fossambault-sur-le-Lac',
			'Gaspé',
			'Gatineau',
			'Gracefield',
			'Granby',
			'Grande-Rivière',
			'Hampstead',
			'Hudson',
			'Huntingdon',
			'Joliette',
			'Kingsey Falls',
			'Kirkland',
			'L\'Ancienne-Lorette',
			'L\'Assomption',
			'L\'Épiphanie',
			'L\'Île-Cadieux',
			'L\'Île-Dorval',
			'L\'Île-Perrot',
			'La Malbaie',
			'La Pocatière',
			'La Prairie',
			'La Sarre',
			'La Tuque',
			'Lac-Delage',
			'Lac-Mégantic',
			'Lac-Saint-Joseph',
			'Lac-Sergent',
			'Lachute',
			'Laval',
			'Lavaltrie',
			'Lebel-sur-Quévillon',
			'Longueuil',
			'Lorraine',
			'Louiseville',
			'Léry',
			'Lévis',
			'Macamic',
			'Magog',
			'Malartic',
			'Maniwaki',
			'Marieville',
			'Mascouche',
			'Matagami',
			'Matane',
			'Mercier',
			'Mirabel',
			'Mont-Joli',
			'Mont-Laurier',
			'Mont-Saint-Hilaire',
			'Mont-Tremblant',
			'Montmagny',
			'Montreal West',
			'Montreal',
			'Montréal-Est',
			'Mount Royal',
			'Murdochville',
			'Métabetchouan–Lac-à-la-Croix',
			'Métis-sur-Mer',
			'Neuville',
			'New Richmond',
			'Nicolet',
			'Normandin',
			'Notre-Dame-de-l\'Île-Perrot',
			'Notre-Dame-des-Prairies',
			'Otterburn Park',
			'Paspébiac',
			'Percé',
			'Pincourt',
			'Plessisville',
			'Pohénégamook',
			'Pointe-Claire',
			'Pont-Rouge',
			'Port-Cartier',
			'Portneuf',
			'Princeville',
			'Prévost',
			'Québec',
			'Repentigny',
			'Richelieu',
			'Richmond',
			'Rimouski',
			'Rivière-du-Loup',
			'Rivière-Rouge',
			'Roberval',
			'Rosemère',
			'Rouyn-Noranda',
			'Saguenay',
			'Saint-Augustin-de-Desmaures',
			'Saint-Basile',
			'Saint-Basile-le-Grand',
			'Saint-Bruno-de-Montarville',
			'Saint-Colomban',
			'Saint-Constant',
			'Saint-Césaire',
			'Saint-Eustache',
			'Saint-Félicien',
			'Saint-Gabriel',
			'Saint-Georges',
			'Saint-Hyacinthe',
			'Saint-Jean-sur-Richelieu',
			'Saint-Joseph-de-Beauce',
			'Saint-Joseph-de-Sorel',
			'Saint-Jérôme',
			'Saint-Lambert',
			'Saint-Lazare',
			'Saint-Lin-Laurentides',
			'Saint-Marc-des-Carrières',
			'Saint-Ours',
			'Saint-Pamphile',
			'Saint-Pascal',
			'Saint-Pie',
			'Saint-Raymond',
			'Saint-Rémi',
			'Saint-Sauveur',
			'Saint-Tite',
			'Sainte-Adèle',
			'Sainte-Agathe-des-Monts',
			'Sainte-Anne-de-Beaupré',
			'Sainte-Anne-de-Bellevue',
			'Sainte-Anne-des-Monts',
			'Sainte-Anne-des-Plaines',
			'Sainte-Catherine',
			'Sainte-Catherine-de-la-Jacques-Cartier',
			'Sainte-Julie',
			'Sainte-Marguerite-du-Lac-Masson',
			'Sainte-Marie',
			'Sainte-Marthe-sur-le-Lac',
			'Sainte-Thérèse',
			'Salaberry-de-Valleyfield',
			'Schefferville',
			'Scotstown',
			'Senneterre',
			'Sept-Îles',
			'Shawinigan',
			'Sherbrooke',
			'Sorel-Tracy',
			'Stanstead',
			'Sutton',
			'Terrebonne',
			'Thetford Mines',
			'Thurso',
			'Trois-Pistoles',
			'Trois-Rivières',
			'Témiscaming',
			'Témiscouata-sur-le-Lac',
			'Val-d\'Or',
			'Valcourt',
			'Varennes',
			'Vaudreuil-Dorion',
			'Victoriaville',
			'Ville-Marie',
			'Warwick',
			'Waterloo',
			'Waterville',
			'Westmount',
			'Windsor'
		],
		'NS' => [
			'Amherst',
			'Antigonish',
			'Bridgewater',
			'Cape Breton (Sydney)',
			'Halifax',
			'Kentville',
			'New Glasgow',
			'Stellarton',
			'Truro',
			'Wolfville',
			'Yarmouth'
		],
		'NB' => [
			'Bathurst',
			'Campbellton',
			'Dieppe',
			'Edmundston',
			'Fredericton',
			'Grand Bay - Westfield',
			'Grand Falls',
			'Miramichi (Chatham - Douglastown)',
			'Moncton',
			'Oromocto',
			'Quispamsis',
			'Riverview',
			'Rothesay',
			'Sackville',
			'Saint John',
			'Shediac',
			'Woodstock'
		],
		'MB' => [
			'Brandon',
			'Dauphin',
			'Flin Flon (incl. Flin Flon, Sask.)',
			'Morden',
			'Portage la Prairie',
			'Selkirk',
			'Steinbach',
			'The Pas',
			'Thompson',
			'Winkler',
			'Winnipeg'
		],
		'BC' => [
			'Abbotsford (Matsqui)',
			'Burnaby',
			'Campbell River',
			'Central Saanich',
			'Chilliwack',
			'Coldstream',
			'Colwood',
			'Comox',
			'Coquitlam',
			'Courtenay',
			'Cranbrook',
			'Dawson Creek',
			'Delta',
			'Esquimalt',
			'Fort St. John',
			'Kamloops',
			'Kelowna',
			'Lake Country',
			'Langford',
			'Langley (incl. Langley District Municipality)',
			'Maple Ridge',
			'Mission',
			'Nanaimo',
			'Nelson',
			'New Westminster',
			'North Cowichan',
			'North Saanich',
			'North Vancouver (incl. North Vancouver District Municipality)',
			'Oak Bay',
			'Parksville',
			'Penticton',
			'Pitt Meadows',
			'Port Alberni',
			'Port Coquitlam',
			'Port Moody',
			'Powell River',
			'Prince George',
			'Prince Rupert',
			'Quesnel',
			'Richmond',
			'Saanich',
			'Salmon Arm',
			'Sechelt',
			'Sidney',
			'Sooke',
			'Squamish',
			'Summerland',
			'Surrey',
			'Terrace',
			'Vancouver',
			'Vernon',
			'Victoria',
			'View Royal',
			'West Kelowna',
			'West Vancouver',
			'Whistler',
			'White Rock',
			'Williams Lake'
		],
		'PE' => [
			'Alberton',
			'Charlottetown',
			'Cornwall',
			'Georgetown',
			'Kensington',
			'Montague',
			'Souris',
			'Stratford',
			'Summerside'
		],
		'SK' => [
			'Estevan',
			'Humboldt',
			'Martensville',
			'Meadow Lake',
			'Melfort',
			'Moose Jaw',
			'North Battleford',
			'Prince Albert',
			'Regina',
			'Saskatoon',
			'Swift Current',
			'Warman',
			'Weyburn',
			'Yorkton'
		],
		'AB' => [
			'Name',
			'Airdrie',
			'Beaumont',
			'Brooks',
			'Calgary',
			'Camrose',
			'Canmore',
			'Chestermere',
			'Cochrane',
			'Cold Lake (Grand Centre)',
			'Edmonton',
			'Fort Saskatchewan',
			'Grande Prairie',
			'High River',
			'Hinton',
			'Lacombe',
			'Leduc',
			'Lethbridge',
			'Lloydminster (incl. Lloydminster (Sask.))',
			'Medicine Hat',
			'Morinville',
			'Okotoks',
			'Red Deer',
			'Spruce Grove',
			'St. Albert',
			'Stony Plain',
			'Strathcona County (incl. Sherwood Park)',
			'Strathmore',
			'Sylvan Lake',
			'Wetaskiwin',
			'Whitecourt',
			'Wood Buffalo (incl. Fort McMurray)'
		],
		'NL' => [
			'Bay Roberts',
			'Clarenville',
			'Conception Bay South',
			'Corner Brook',
			'Deer Lake',
			'Gander',
			'Grand Falls - Windsor',
			'Happy Valley - Goose Bay',
			'Labrador City',
			'Marystown',
			'Mount Pearl',
			'Paradise',
			'Portugal Cove - St. Philip\'s',
			'St. John\'s',
			'Stephenville',
			'Torbay'
		]
	);
}

function getProvinces() {
	return array(
		'ON' => 'Ontario',
		'QC' => 'Quebec',
		'NS' => 'Nova Scotia',
		'NB' => 'New Brunswick',
		'MB' => 'Manitoba',
		'BC' => 'British Columbia',
		'PE' => 'Prince Edward Island',
		'SK' => 'Saskatchewan',
		'AB' => 'Alberta',
		'NL' => 'Newfoundland and Labrador'
	);
}

function getCitiesByProvince($code){
	return  getCities()[$code];
}

function getProvinceByCode($code){
	return  getProvinces()[$code];
}

